name: cached_s5_image
description: "Cached Image Provider for S5."
repository: https://github.com/s5-dev/cached_s5_image
homepage: https://github.com/s5-dev/cached_s5_image

version: 0.0.9

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_s5_manager: ^1.2.2
  flutter:
    sdk: flutter
  flutter_thumbhash: ^0.1.0+1
  logger: ^2.4.0
  s5: ^0.2.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

topics:
  - cache
  - s5
  - thumbhash
  - image

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
